<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.81.0" />


<title>What went wrong for Kentucky basketball this season?  - Robert Killgore Kentucky Sports Data Project</title>
<meta property="og:title" content="What went wrong for Kentucky basketball this season?  - Robert Killgore Kentucky Sports Data Project">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/robertkillgore">GitHub</a></li>
    
    <li><a href="https://twitter.com/bobkillgore">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">9 min read</span>
    

    <h1 class="article-title">What went wrong for Kentucky basketball this season? </h1>

    
    <span class="article-date">2021-04-02</span>
    

    <div class="article-content">
      
<script src="/2021/04/02/what-went-wrong-for-kentucky-basketball-this-season/index_files/header-attrs/header-attrs.js"></script>


<p>The bluebloods of college basketball were not their usual selves in the 2020-2021 season, Kentucky being the most disappointing of them all. The Wildcats went 9-16 this year and finished 8-9 in conference play, missing the NCAA tournament for the first time since 2013. To begin looking at what went wrong for Kentucky this season, let’s start by grabbing the games logs for each team of the 2020-2021 season.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.0.5     ✓ dplyr   1.0.3
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>logs21 &lt;- read_csv(&quot;logs21.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   Season = col_character(),
##   Date = col_date(format = &quot;&quot;),
##   TeamFull = col_character(),
##   Opponent = col_character(),
##   HomeAway = col_character(),
##   W_L = col_character(),
##   URL = col_character(),
##   Conference = col_character(),
##   Team = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<p>To get started, I’m going to look at cumulative point differential for the teams in the SEC. You would think a team with a positive point differential should be at least .500 while a team with a negative point differential should be below .500.</p>
<pre class="r"><code>sec &lt;- logs21 %&gt;% 
  mutate(pointdifferential = TeamScore - OpponentScore) %&gt;% group_by(Team) %&gt;% mutate(CumPointDiff = cumsum(pointdifferential)) %&gt;% filter(Conference == &quot;SEC&quot;)</code></pre>
<p>Now that we got the cumulative point differential for each team in the SEC, let’s compare Kentucky to the 22-6 Arkansas Razorbacks and the 13-14 Auburn Tigers.</p>
<pre class="r"><code>uk &lt;- sec %&gt;% filter(Team == &quot;Kentucky&quot;) 
ark &lt;- sec %&gt;% filter(Team == &quot;Arkansas&quot;)
aub &lt;- sec %&gt;% filter(Team== &quot;Auburn&quot;)</code></pre>
<pre class="r"><code>ggplot() + 
  geom_step(data=sec, aes(x=Date, y=CumPointDiff, group=Team), color=&quot;light grey&quot;) +
  geom_step(data=uk, aes(x=Date, y=CumPointDiff, group=Team), color=&quot;blue&quot;) + 
  geom_step(data=ark, aes(x=Date, y=CumPointDiff, group=Team), color=&quot;red&quot;) +
  geom_step(data=aub, aes(x=Date, y=CumPointDiff, color=Team), color=&quot;orange&quot;) +
  annotate(&quot;text&quot;, x=(as.Date(&quot;2021-01-02&quot;)), y=20, label=&quot;Auburn&quot;) +
  annotate(&quot;text&quot;, x=(as.Date(&quot;2021-1-16&quot;)), y=-30, label=&quot;Kentucky&quot;) +
  annotate(&quot;text&quot;, x=(as.Date(&quot;2021-02-01&quot;)), y=283, label=&quot;Arkansas&quot;) +
  labs(
    x=&quot;Date&quot;, 
    y=&quot;Cumulative Point Differential&quot;, 
    title=&quot;Kentucky&#39;s Inability to win close games&quot;, 
    subtitle=&quot;The Wildcats would keep the game close but couldn&#39;t find a way to win&quot;, 
    caption=&quot;Source: NCAA | By Robert Killgore&quot;) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 17, face = &quot;bold&quot;),
    axis.title = element_text(size = 13), 
    plot.subtitle = element_text(size=11), 
    panel.grid.minor = element_blank()
    ) </code></pre>
<p><img src="/2021/04/02/what-went-wrong-for-kentucky-basketball-this-season/index_files/figure-html/unnamed-chunk-5-1.png" width="672" />
Kentucky ended up finishing the year with a positive point differential, something not typically seen in a 9-16 team. One reason for this is the Wildcats were 2-8 in games decided by 4 points or less, including a one point loss against Mississippi State in the SEC tournament. Say they go 5-5 instead, Kentucky ends up 12-13, a slightly below-average team.</p>
<p>Now, let’s look at Kentucky’s total turnovers and steals compared to the rest of the SEC. If a team forces a lot of turnovers in a given game, they steal away their opponents precious possessions and increase the likelihood of winning that game. Let’s see how well Kentucky kept care of the ball and how well they wrecked havoc on the defensive end.</p>
<pre class="r"><code>library(tidyverse)
library(ggalt)</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggalt&#39;:
##   method                  from   
##   grid.draw.absoluteGrob  ggplot2
##   grobHeight.absoluteGrob ggplot2
##   grobWidth.absoluteGrob  ggplot2
##   grobX.absoluteGrob      ggplot2
##   grobY.absoluteGrob      ggplot2</code></pre>
<pre class="r"><code>possessions &lt;- logs21 %&gt;%
  group_by(Team, Conference) %&gt;% 
  summarise(
    possessionslost = sum(TeamTurnovers), 
    Steals = sum(TeamSteals)) %&gt;%
  filter(Conference == &quot;SEC&quot;)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;Team&#39;. You can override using the `.groups` argument.</code></pre>
<p>I want to create a graph which highlights teams total turnovers and steals. I will use a dumbbell chart to show this, which shows the difference between two things on a number line. I’m going to make turnovers blue and steals purple. The total amount of turnovers and steals for each team will be on the x-axis and the y-axis will have the SEC teams, reordered by the amount of turnovers.</p>
<pre class="r"><code>ggplot() + 
  geom_dumbbell(
    data=possessions, 
    aes(y=reorder(Team, possessionslost), x=possessionslost, xend=Steals),
    size = 1,
    color = &quot;grey&quot;,
    colour_x = &quot;blue&quot;,
    colour_xend = &quot;purple&quot;) + 
  theme_minimal() +
  labs(
    x=&quot;Date&quot;, 
    y=&quot;reorder(Team, possessionslost)&quot;, 
    title=&quot;Kentucky couldn&#39;t force enough turnovers to make up their own&quot;, 
    subtitle=&quot;The Wildcats were middle of the pack in turnovers but 2nd to last in steals in the SEC&quot;, 
    caption=&quot;Source: NCAA | By Robert Killgore&quot;) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, face = &quot;bold&quot;),
    axis.title = element_text(size = 11), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
    ) </code></pre>
<p><img src="/2021/04/02/what-went-wrong-for-kentucky-basketball-this-season/index_files/figure-html/unnamed-chunk-9-1.png" width="672" />
Kentucky ended up the year with less turnovers than top teams like Alabama and Arkansas, but had far less steals than them. Teams that made the tournament like LSU, Tennessee, and Alabama lines from steals and turnovers were smaller than Kentucky’s, showing how important turnover differential is to winning.</p>
<p>Now, let’s jump to field goal percentage and compare Kentucky’s field goal shooting percentage to the rest of the power five teams. In the John Calipari era, Kentucky has had elite shooters like Devin Booker, Tyler Herro, and Malik Monk. Freshman guard Brandon Boston Jr was supposed to be that guy, but finished the season shooting 30% from three and shooting 35.5% from the field.</p>
<pre class="r"><code>logs21 &lt;- read_csv(&quot;logs21.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   Season = col_character(),
##   Date = col_date(format = &quot;&quot;),
##   TeamFull = col_character(),
##   Opponent = col_character(),
##   HomeAway = col_character(),
##   W_L = col_character(),
##   URL = col_character(),
##   Conference = col_character(),
##   Team = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<p>I only care about the power five teams, so let’s get rid of the non-power five teams</p>
<pre class="r"><code>powerfive &lt;- c(&quot;SEC&quot;, &quot;Big Ten&quot;, &quot;Pac-12&quot;, &quot;Big 12&quot;, &quot;ACC&quot;)</code></pre>
<pre class="r"><code>powerfive &lt;- logs21 %&gt;% filter(Conference %in% powerfive)</code></pre>
<p>Next, I need to find out the field goal percent average for the power five throughout the season and Kentucky’s. Then using that information, we can compare Kentucky’s field goal percentage throughout the season to the power five.</p>
<pre class="r"><code>fieldgoalaverage &lt;- logs21 %&gt;% group_by(Date) %&gt;% summarise(mean_fieldgoalshooting=mean(TeamFGPCT))</code></pre>
<pre class="r"><code>uk &lt;- logs21 %&gt;% filter(Team == &quot;Kentucky&quot;)</code></pre>
<pre class="r"><code>ggplot() + 
  geom_line(data = powerfive, aes(x=Date, y=TeamFGPCT, group=Team), color=&quot;grey&quot;) + geom_line(data=uk, aes(x=Date, y=TeamFGPCT), color=&quot;blue&quot;) + 
  geom_line(data=fieldgoalaverage, aes(x=Date, y=mean_fieldgoalshooting), color=&quot;black&quot;) + 
  scale_y_continuous(limits = c(0, .70)) + 
  annotate(&quot;text&quot;, x=(as.Date(&quot;2021-1-16&quot;)), y=.36, label=&quot;uk&quot;) +
  annotate(&quot;text&quot;, x=(as.Date(&quot;2020-12-13&quot;)), y=.49, label=&quot;powerfive average&quot;) +
labs(x=&quot;Date&quot;, y=&quot;TeamFGPCT&quot;, title=&quot;Kentucky was not a good shooting team&quot;, subtitle=&quot;The Wildcats were constantly below the power five average shooting percentage all season&quot;, caption=&quot;Source: NCAA | By Robert Killgore&quot;) + theme_minimal() + theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    axis.title = element_text(size = 10), 
    plot.subtitle = element_text(size=11), 
    panel.grid.minor = element_blank()
    ) </code></pre>
<p><img src="/2021/04/02/what-went-wrong-for-kentucky-basketball-this-season/index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Besides the spike in early January, Kentucky was constantly below the power five average most of the season. Not exactly a winning formula.</p>
<p>Now, let’s see where Kentucky ranked in the SEC in total offensive rebounds and compare them with th power five. More offensive rebounds should lead to teams with more chances to score</p>
<pre class="r"><code>library(tidyverse)
library(ggbeeswarm)
library(ggrepel)</code></pre>
<pre class="r"><code>offensiverebounds &lt;- logs21 %&gt;% group_by(Team, Conference) %&gt;% summarise(totaloffensiverebounds= sum(TeamOffRebounds)) %&gt;% filter(Conference== &quot;Big Ten&quot;| Conference== &quot;SEC&quot;| Conference== &quot;Big 12&quot;| Conference== &quot;ACC&quot;| Conference== &quot;Pac-12&quot;) %&gt;% ungroup() </code></pre>
<pre><code>## `summarise()` has grouped output by &#39;Team&#39;. You can override using the `.groups` argument.</code></pre>
<p>Next, we have to filter out for Kentucky. Then we create a beeswarm plot comparing power five teams in offensive rebounds</p>
<pre class="r"><code>uk &lt;- offensiverebounds %&gt;% filter(Team== &quot;Kentucky&quot;)</code></pre>
<pre class="r"><code>ggplot() + geom_text_repel(
    data=uk, 
    aes(x=Conference, y=totaloffensiverebounds, label=Team))+ geom_beeswarm(data=offensiverebounds, groupOnX=TRUE, aes(x=Conference, y=totaloffensiverebounds), color=&quot;grey&quot;) +  geom_point(data=uk, aes(x=Conference, y=totaloffensiverebounds), color=&quot;blue&quot;)+
  labs(
    x=&quot;Date&quot;, 
    y=&quot;Total Offensive Rebounds&quot;, 
    title=&quot;Kentucky Was Not a Bad Offensive Rebounding Team&quot;, 
    subtitle=&quot;The Wildcats were among the upper half of the SEC in offensive rebounds&quot;, 
    caption=&quot;Source: NCAA | By Robert Killgore&quot;) +
  theme_minimal() +  theme(
    plot.title = element_text(size = 15, face = &quot;bold&quot;),
    axis.title = element_text(size = 10), 
    plot.subtitle = element_text(size=11), 
    panel.grid.minor = element_blank()
    ) </code></pre>
<p><img src="/2021/04/02/what-went-wrong-for-kentucky-basketball-this-season/index_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>With the new information, we have let’s see how Kentucky underperformed this season. Let’s look at assists, a good metric for a team’s success. First let’s set up a scatterplot with the amount of wins each team had this year on the y-axis and team’s total assists on the x-axis</p>
<pre class="r"><code>winlosslogs &lt;- logs21 %&gt;% 
  mutate(
    winloss = case_when(
      grepl(&quot;W&quot;, W_L) ~ 1, 
      grepl(&quot;L&quot;, W_L) ~ 0)
)</code></pre>
<pre class="r"><code>dimes &lt;- winlosslogs %&gt;% 
  group_by(Team) %&gt;% 
  summarise(
    Wins = sum(winloss), 
    TotalAssists = sum(TeamAssists)
    )</code></pre>
<p>Now we can create a scatterplot that shows the relationship between total assists and team wins. First, we have to find out what the R squared value is, which tells us how much assists factor in winning</p>
<pre class="r"><code>fit &lt;- lm(Wins ~ TotalAssists, data = dimes)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Wins ~ TotalAssists, data = dimes)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.6041  -2.5473   0.2046   2.7052  10.0404 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -3.630841   0.843546  -4.304 2.19e-05 ***
## TotalAssists  0.050618   0.002646  19.133  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.678 on 345 degrees of freedom
## Multiple R-squared:  0.5148, Adjusted R-squared:  0.5134 
## F-statistic: 366.1 on 1 and 345 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The R squared value is 0.5134, which means that assists predicts about 51.34 percent of the variance in wins. That is a lot. I can also find out how teams underperformed or overperformed their win totals from the coefficients found above and the amount of assists a team had using the equation y=mx +b. Plugging in the numbers for Kentucky, it would like .050618 times 312(number of assists they had) + -3.630841. That equals 12.16, which means according to our model Kentucky should have won 12 games in the 2020-2021 season just looking at total assists. Let’s see how this looks in a scatterplot this season among teams in the NCAA this season, Kentucky the blue dot.</p>
<pre class="r"><code>uk &lt;- dimes %&gt;% filter(Team == &quot;Kentucky&quot;)</code></pre>
<pre class="r"><code>ggplot() +
  geom_point(data=dimes, aes(x=TotalAssists, y=Wins))  +
  geom_smooth(data=dimes, aes(x=TotalAssists, y=Wins), method=&quot;lm&quot;) +
  geom_point(data=uk, aes(x=TotalAssists, y=Wins), color=&quot;blue&quot;) +
  labs(
    x=&quot;TotalAssists&quot;, 
    y=&quot;Team&quot;, 
    title=&quot;Kentucky Underperformed Their Expected Win Total in Assists This Season &quot;, 
    subtitle=&quot;The Wildcats should have won 12 games just looking at total assists &quot;, 
    caption=&quot;Source: NCAA | By Robert Killgore&quot;) +
  theme_minimal() +  theme(
    plot.title = element_text(size = 15, face = &quot;bold&quot;),
    axis.title = element_text(size = 10), 
    plot.subtitle = element_text(size=11), 
    panel.grid.minor = element_blank()
    ) </code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/2021/04/02/what-went-wrong-for-kentucky-basketball-this-season/index_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>Kentucky played better than what their record said, the data showing they should have finished with 12 or 13 wins. It will be interesting to see if this year was just a fluke or a the start of the end of the Calipari Era in Lexington.</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
  </body>
</html>

